apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gemma-1-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-gemma-1-7b
  template:
    metadata:
      labels:
        app: vllm-gemma-1-7b
    spec:
      serviceAccountName: default
      containers:
        - name: inference-server
          image: vllm/vllm-openai:v0.8.5.post1
          resources:
            requests:
              cpu: "4"
              memory: "50Gi"
              ephemeral-storage: 100Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "4"
              memory: "50Gi"
              ephemeral-storage: 100Gi
              nvidia.com/gpu: "1"
          args:
            - --model=$(MODEL)
            - --tensor-parallel-size=1
            - --gpu-memory-utilization=0.9
            - --max_model_len=4096
            - --max-num-seqs=256
            - --dtype=bfloat16
          env:
            - name: MODEL
              value: gimarchetti/gemma1-7b-openmath
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          lifecycle:
            preStop:
              sleep:
                seconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3600
            initialDelaySeconds: 2
            periodSeconds: 1
            httpGet:
              path: /health
              port: http
              scheme: HTTP
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-gemma-1-7b
spec:
  selector:
    app: vllm-gemma-1-7b
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vllm-gemma-1-7b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vllm-gemma-1-7b
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: External
      external:
        metric:
          name: prometheus.googleapis.com|inference_pool_average_kv_cache_utilization|gauge
          selector:
            matchLabels:
              metric.labels.name: vllm-gemma-1-7b
        target:
          type: AverageValue
          averageValue: 10m
